# Generated by Django 4.2.5 on 2023-10-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image_alter_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../user_profile', upload_to='images/'),
        ),
    ]
