# Generated by Django 4.2.5 on 2023-10-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='../category_default', upload_to='images/'),
        ),
    ]
